---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release-docker:
    name: "Pre Release Docker"
    runs-on: "ubuntu-latest"


    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: docker/setup-qemu-action@v1

    - uses: docker/setup-buildx-action@v1

    - uses: docker/login-action@v1
      with:
        username: "${{ secrets.DOCKER_HUB_USER }}"
        password: "${{ secrets.DOCKER_HUB_TOKEN }}"

    - name: "Build and push docker image"
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        tags: "${{ secrets.DOCKER_REPO }}:latest"
