packages:
  - nvidia-container-toolkit
  - kmod-nvidia-6.7.7-200.fc39.x86_64-550.67-1.fc39.x86_64
  - nvidia-driver-cuda-550.67-1.fc39.x86_64
  - nvidia-driver-NVML-550.67-1.fc39.x86_64
  - nvidia-kmod-common-550.67-1.fc39.noarch

recommends: false

repos:
  - nvidia-container-toolkit
  - fedora-nvidia
  - fedora

add-files:
  - ["nvidia-container.pp", "/usr/share/selinux/packages/nvidia-container.pp"]

postprocess:
  - |
    #!/usr/bin/env bash
    set -euxo pipefail
    semodule --verbose --install /usr/share/selinux/packages/nvidia-container.pp
