packages:
  - nvidia-container-toolkit
  - kmod-nvidia-6.5.9-300.fc39.x86_64-545.29.06-1.fc39.x86_64
  - nvidia-driver-cuda-545.29.06-2.fc39.x86_64
  - nvidia-driver-NVML-545.29.06-2.fc39.x86_64
  - nvidia-kmod-common-545.29.06-1.fc39.noarch

recommends: false

repos:
  - nvidia-container-toolkit
  - fedora-nvidia
  - fedora

add-files:
  - ["nvidia-container.pp", "/usr/share/selinux/packages/nvidia-container.pp"]

postprocess:
  - |
    #!/usr/bin/env bash
    set -euxo pipefail
    semodule --verbose --install /usr/share/selinux/packages/nvidia-container.pp
