# https://coreos.github.io/coreos-assembler/working/
# https://coreos.github.io/rpm-ostree/treefile/

include:
  - fedora-coreos.yaml
  - nvidia.yaml

packages:
  # so we can inspect things with lspci
  - pciutils

ostree-layers:
  - gen-overlay/substrateos

ostree-override-layers:
  - overlay/50substrateos

postprocess:
  - |
    setcap cap_net_bind_service=+ep /usr/bin/caddy
