# https://coreos.github.io/coreos-assembler/working/
# https://coreos.github.io/rpm-ostree/treefile/

include:
  - fedora-coreos.yaml
  - nvidia.yaml

ostree-layers:
  - gen-overlay/containers
  - gen-overlay/resourcedirs

ostree-override-layers:
  - overlay/50containers-storage-conf
