version: '3.6'

services:
  transcriber:
    platform: "linux/amd64"
    build:
      context: ./../../transcriber
      dockerfile: Dockerfile
    ports:
      - 8090:8000
  assister:
    platform: "linux/amd64"
    build:
      context: ./../../assister
      dockerfile: Dockerfile
    ports:
      - 8091:8080
  translator:
    platform: "linux/amd64"
    build:
      context: ./../../translator
      dockerfile: Dockerfile
    ports:
      - 8092:8000
