cluster_domain = "plane.test"

[nats]
hosts = ["127.0.0.1"]

[agent]
ip = "127.0.0.1"

[proxy]
bind_ip = "127.0.0.1"
http_port = "8080"
https_port = "4333"

# Uncomment to enable path-based routing
# (note that DNS-based routing, including dev-curl.sh, will no longer work.)
# allow_path_routing = true

[cert]
key_path = "sample-config/auth/site-key.pem"
cert_path = "sample-config/auth/site-cert.pem"
