FROM ghcr.io/ggml-org/llama.cpp:server-cuda-b6121
# Based on https://raw.githubusercontent.com/ggml-org/llama.cpp/refs/heads/master/tools/server/README.md
COPY images/llama-server/openapi.json /openapi.json
