FROM scratch
WORKDIR  /treehouse
COPY images/template-treehouse/app/ /treehouse/app/
COPY images/template-treehouse/lib/ /treehouse/lib/
COPY images/template-treehouse/style/ /treehouse/style/
COPY images/template-treehouse/vnd/ /treehouse/vnd/
COPY images/template-treehouse/index.html /treehouse/index.html
