FROM quay.io/fedora/fedora-coreos:stable

COPY --from=ghcr.io/ublue-os/ucore-kmods:stable-20231005 /rpms/kmods/nvidia/*.rpm /tmp/rpms/nvidia/
COPY --from=ghcr.io/ublue-os/ucore-kmods:stable-20231005 /rpms/kmods/zfs/*.rpm /tmp/rpms/zfs/

COPY etc /etc
COPY usr /usr

RUN mkdir -p /var/lib/alternatives \
    && rpm-ostree install \
        /tmp/rpms/zfs/*.rpm \
    && curl -L https://negativo17.org/repos/fedora-nvidia.repo -o /etc/yum.repos.d/fedora-nvidia.repo \
    && rpm-ostree install /tmp/rpms/nvidia/ublue-os-ucore-nvidia-*.rpm \
    && sed -i '0,/enabled=0/{s/enabled=0/enabled=1/}' /etc/yum.repos.d/nvidia-container-toolkit.repo \
    && rpm-ostree install \
        /tmp/rpms/nvidia/kmod-nvidia-*.rpm \
        nvidia-driver-cuda \
        nvidia-container-toolkit \
    && sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/nvidia-container-toolkit.repo \
    && semodule --verbose --install /usr/share/selinux/packages/nvidia-container.pp \
    && systemctl disable zincati.service \
    && mv /var/lib/alternatives /staged-alternatives \
    && rm -fr /tmp/* /var/* \
    && ostree container commit \
    && mkdir -p /var/lib && mv /staged-alternatives /var/lib/alternatives \
    && mkdir -p /tmp /var/tmp \
    && chmod -R 1777 /tmp /var/tmp

LABEL org.opencontainers.image.source https://github.com/ajbouh/substrate
