#!/bin/bash

set -eo pipefail
set -x

HERE=$(cd $(dirname $0)/..; pwd)

CUE_MODULE=github.com/ajbouh/substrate

nomad_deploy_job() {
  NOMAD_JOB=$HERE/.gen/nomad/nomad-job-$NAMESPACE.json
  mkdir -p $(dirname $NOMAD_JOB)

  nomad_server_url=$1
  nomad_job_name=$2
  shift 2

  base_job_expr="nomad.jobs[\"$nomad_job_name\"]"
  job_expr="$base_job_expr"

  nomad_job_services=()
  for nomad_job_service in $(cue_export text $CUE_MODULE:deploy "strings.Join(list.Concat([for tg in ($base_job_expr).taskgroups {[for t in tg.tasks { t.name }]}]), \" \")"); do
    nomad_job_services+=("$nomad_job_service")
  done

  # Need to push before the repo digests are available
  # docker_compose $DOCKER_COMPOSE_YML push "${nomad_job_services[@]}"

  # Unify the job expression with specific repo digests so that the job is exactly what we expect.
  for nomad_job_service in "${nomad_job_services[@]}"; do
    nomad_job_image=$(cue_export text $CUE_MODULE:deploy "$base_job_expr.#tasks[\"$nomad_job_service\"].config.image")
    repo_digest=$(docker inspect ${nomad_job_image} --format "{{index .RepoDigests 0}}")
    job_expr="$job_expr & {#tasks: \"${nomad_job_service}\": config: image: \"$repo_digest\"}"
  done

  # Trim the leading "nomad" characters from given expr, so we can use the unified expression instead
  # NB there's probably a more general way to do this, but this hack works for now.
  cue_export json $CUE_MODULE:deploy "{Job: (${job_expr})}" > $NOMAD_JOB

  curl < $NOMAD_JOB --request POST --data @- $nomad_server_url/v1/jobs
}

DRONE_IP=$(cue_export text $CUE_MODULE:external 'tailscale.drone_ip')
NOMAD_SERVER_HOSTNAME=$DRONE_IP
NOMAD_SERVER_URL=http://$NOMAD_SERVER_HOSTNAME:4646

# Deploy plane-drone and substratefs to nomad
nomad_deploy_job $NOMAD_SERVER_URL jamsocket_drone
