FROM quay.io/go-skynet/local-ai:latest

RUN cd /build/models && wget --content-disposition https://huggingface.co/TheBloke/Airoboros-L2-13B-2.1-GGML/resolve/main/airoboros-l2-13b-2.1.ggmlv3.Q2_K.bin?download=true