name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore: [ "/docs" ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "/docs" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest-16-cores

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
      with:
        cache-on-failure: true

    - name: Install cargo-nextest
      run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

    - name: Run tests
      run: cargo nextest run -j 5

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-data
        path: dev/test-scratch
